# Generated by Django 3.2.5 on 2021-07-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerapp', '0002_alter_product_des'),
    ]

    operations = [
        migrations.CreateModel(
            name='offerproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=50)),
                ('offer_desc', models.CharField(max_length=150)),
                ('offer_img', models.ImageField(upload_to='offer')),
            ],
        ),
    ]
