# Generated by Django 3.2.5 on 2021-07-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerapp', '0004_offerproduct_offer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerproduct',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=10),
            preserve_default=False,
        ),
    ]
